### ISSUE TITLE
Documentation of how customize the loaders

### ISSUE THREAD

**Issue by raphaelfabeni** [raphaelfabeni/css-loader#2]
For me of course that is simple to customize the loaders but it must have a simple and directly explanation/example of how to customize the colors and the sizes of loaders.

**Comment by vikaskyadav** [comment]
How do you plan or wish to explain such things to naive users?

**Comment by raphaelfabeni** [comment]
@vikaskyadav this is something that I thought some days ago.
There are two ways to do that:

The most simple is to show an example maybe and the other one, is show how to clone/download the project and change the _variables_ that build the loaders.

**Comment by OndrejSpanel** [comment]
This would be nice. I have added your loader to my page and I like it a lot, still I would prefer the background a bit more transparent. I have no idea how to achieve this (I have almost no CSS experience).

**Comment by raphaelfabeni** [comment]
@OndrejSpanel great and sorry about that! I will try work on it soon!
