### ISSUE TITLE
Border option don't work on IE EDGE

### ISSUE THREAD

**Issue by danilosantosdev** [raphaelfabeni/css-loader#24]
The border option of the loader it's not working well on IE EDGE.

I attach a gif showing the problem.
![css_loader_ie_edge_issue](https://cloud.githubusercontent.com/assets/2335679/22814084/ca17d58e-ef37-11e6-8225-54cd9ed6b004.gif)

**Comment by raphaelfabeni** [comment]
Thanks @danilosantosdev !
As soon I have some time I'm going to take a loot at it.

**Comment by raphaelfabeni** [comment]
I saw here and I think the problem is related to the Sass variable interpolation. Inside the `@keyframes` animation, we have something like this:

```sass
left: calc(100% - #{$loader-border--width})
```

If I change for `100%`, it works. But doing that, the border will overflow the screen.

**Comment by danilosantosdev** [comment]
You're welcome @raphaelfabeni .

Maybe in a few months I could contribute to the project.

**Comment by raphaelfabeni** [comment]
Let me know when you could help w/ this :)
