### ISSUE TITLE
Loader aberto sem a classe is-active

### ISSUE THREAD

**Issue by gabrielferreiraa** [raphaelfabeni/css-loader#25]
Fala @raphaelfabeni, beleza?
Coloquei a DIV sem a classe `is-active` e ela mesmo assim fica sendo mostrada na cor branca(foto), quando eu adiciono a classe `is-active` ela funciona tudo certo.

Precisei usar opacity, mas está ai haha
Muito bom o loader, valeu!

Browser: Chrome
![image](https://cloud.githubusercontent.com/assets/17201177/22985461/a39e1f56-f38f-11e6-90a8-5811135f6833.png)

![image](https://cloud.githubusercontent.com/assets/17201177/22985447/96cf34ae-f38f-11e6-887b-54c3e6117400.png)

**Comment by raphaelfabeni** [comment]
Boa @gabrielferreiraa ! Vou dar uma olhada depois.
Obrigado pelo feedback.
