### ISSUE TITLE
Consider progress stripe animation direction to move backwards.

### ISSUE THREAD

**Issue by kerryj89** [raphaelfabeni/css-loader#27]
I read this recently http://ux.stackexchange.com/questions/18361/why-do-progress-bars-animate-backwards

I wondered why Bootstrap had it moving backwards as well as other progress bars that I have encountered.  It seems like moving to the left is the default direction in many places.  I only learned of it recently and thought it was something to consider.  Not an issue, per se.  Apologies if this isn't the right place for it.

Excellent work so far!

Edit:  Just realized that these loaders were indeterminate, so it may not apply.

**Comment by raphaelfabeni** [comment]
Hey @kerryj89 ! 
Thanks for spend your time analysing it.
And I think it's make sense. Maybe we could apply `backwards` as default animation and let this currently animation as a data paramater, like `data-inverse` maybe, so the user could chose between both.

🤘
