### ISSUE TITLE
loader-default not working with repo compiled css

### ISSUE THREAD

**Issue by pldg** [raphaelfabeni/css-loader#37]
If copy-paste the compiled css in this repo:

- `loader-default` not working https://jsbin.com/yugutuzuda/edit?html,output

- `loader-double` works fine https://jsbin.com/xaqezoqece/edit?html,output

I didn't try all the other.

**Comment by raphaelfabeni** [comment]
Hey @pldg ! I just copied the CSS inside the dist folder and copied inside the JSbin you sent me and it worked. Probably it was something you forgot to copy.
Tks :)

**Comment by pldg** [comment]
Hi @raphaelfabeni, the problem is in the `README.md` in *default* chapter.

The link *CSS* is pointing to [loader-ball](https://raw.githubusercontent.com/raphaelfabeni/css-loader/master/dist/loader-ball.css) instead of [loader-default](https://raw.githubusercontent.com/raphaelfabeni/css-loader/master/dist/loader-default.css).

I was reading the doc and followed that link to copy-paste into jsbin.

Thanks this repo! :)
