### ISSUE TITLE
Single Div Loading

### ISSUE THREAD

**Issue by razamu15** [raphaelfabeni/css-loader#49]
There is a easy way that the amazing css loaders in this library can be adapted for single div use cases with the use of html5 iframes. For my own use and addressing issues such as #40 which many beginners may have, I think it would be beneficial to add to the readme some documentation about embedding a barebones html page into an iframe for the said use case. 

furthermore, the pre existing examples make this very easy to make a part of the library by just removing the container class divs, and adding directives in the readme to use iframes like so:
<iframe src="/examples/loader-ball.html" ></iframe>

I would be happy to submit a pr with these changes.

**Comment by raphaelfabeni** [comment]
Hey @razamu15 ! Sorry.. currently I'm very busy and I'm not able to spend more time to implement more features. I just didn't understand your idea here: what is the advantage to load in an HTML file?
