### ISSUE TITLE
Add a License file!

### ISSUE THREAD

**Issue by terremoth** [raphaelfabeni/css-loader#66]
Hello!
It is very important for other people to use your library if your project have a License file.
I suggest some GPL-based license! If you want I can make a pull request.

**Comment by raphaelfabeni** [comment]
Hey @terremoth ! The repo already has a [MIT license](https://github.com/raphaelfabeni/css-loader#license). 
I don't intend to make any updates here soon. I can take a look to understand better the difference between MIT and GPL.

**Comment by terremoth** [comment]
> Hey @terremoth ! The repo already has a [MIT license](https://github.com/raphaelfabeni/css-loader#license). I don't intend to make any updates here soon. I can take a look to understand better the difference between MIT and GPL.

Would you mind to create a file "LICENSE" so the web-crawlers could automatically identify/detect it?

**Comment by terremoth** [comment]
Github has its helper to create automatically. If you want I can make a PR with the MIT license on it

**Comment by raphaelfabeni** [comment]
Could you please explain me what are the benefits of a GPL license?

**Comment by raphaelfabeni** [comment]
Would be great @terremoth 🤟
If you have time of course!

**Comment by terremoth** [comment]
I am purposing to create a file with the license inside, like most github repos. You just linked the license at Readme.

## About the GPL

Different from the MIT license, the GPL licenses guarantees that other people will have the right to look, modify and distribute your library, and prohibiting people to take your code, close the source and sell it back to you without you know you made that code, for example.

It basically prohibits others from take others freedom away! It means your CSS-Loader will be free and everyone that would extend-it, use it or redistribute-it SHOULD let it free.
> free does not means "free beer (gratis)", it means freedom ("liberdade para sempre sem que possam tira-la de você ou de outros fechando o código e fazendo o que bem entendem").

**Comment by terremoth** [comment]
The MIT license basically permits your code to be modified, but others to take it and close its source and sell it, without letting people look its code, or even know YOU created, for example...

**Comment by terremoth** [comment]
Let me know if you want me to create a LICENSE file with the MIT license or a GPL-like license

**Comment by raphaelfabeni** [comment]
Got it! Thanks for spending your time explaining to me. GPL looks good then.

**Comment by terremoth** [comment]
So here goes: https://github.com/raphaelfabeni/css-loader/pull/67

**Comment by terremoth** [comment]
I will also change the README.md

**Comment by raphaelfabeni** [comment]
Done 👍 👍
Thank you!
